# Generated by Django 2.2 on 2020-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст'),
        ),
    ]
